services:
  postgres:
    image: postgres:17.4-alpine
    container_name: postgres-todo-list
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: "America/Sao_Paulo"
      PGTZ: "America/Sao_Paulo"
    volumes:
      - postgres_todo_list_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_todo_list_data: